//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.07 at 01:56:53 PM CEST 
//


package appConfigurationClasses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the appConfigurationClasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: appConfigurationClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Clientconfig }
     * 
     */
    public Clientconfig createClientconfig() {
        return new Clientconfig();
    }

    /**
     * Create an instance of {@link Clientconfig.Endpoints }
     * 
     */
    public Clientconfig.Endpoints createClientconfigEndpoints() {
        return new Clientconfig.Endpoints();
    }

    /**
     * Create an instance of {@link Clientconfig.Endpoints.Endpoint }
     * 
     */
    public Clientconfig.Endpoints.Endpoint createClientconfigEndpointsEndpoint() {
        return new Clientconfig.Endpoints.Endpoint();
    }

    /**
     * Create an instance of {@link Clientconfig.Endpoints.Endpoint.Attributes }
     * 
     */
    public Clientconfig.Endpoints.Endpoint.Attributes createClientconfigEndpointsEndpointAttributes() {
        return new Clientconfig.Endpoints.Endpoint.Attributes();
    }

    /**
     * Create an instance of {@link Clientconfig.Endpoints.Endpoint.Attributes.Attribute }
     * 
     */
    public Clientconfig.Endpoints.Endpoint.Attributes.Attribute createClientconfigEndpointsEndpointAttributesAttribute() {
        return new Clientconfig.Endpoints.Endpoint.Attributes.Attribute();
    }

}
